/**
 * Wavefront OBJ Exporter — converts MeshData to OBJ text format.
 *
 * Format:
 * - Comments starting with #
 * - v (vertex) lines
 * - vn (vertex normal) lines
 * - f (face) lines referencing v/vn indices (1-based)
 */

import type { MeshData } from '../../types/cad';

export interface OBJExportResult {
  obj: string;
  mtl?: string;
}

export function exportOBJ(meshes: MeshData[], name = 'OpenCAD'): OBJExportResult {
  let obj = `# ${name} OBJ Export\n`;
  obj += `# Generated by OpenCAD\n\n`;

  let vertexOffset = 0;
  let normalOffset = 0;

  for (const mesh of meshes) {
    const vertexCount = mesh.vertices.length / 3;
    const normalCount = mesh.normals.length / 3;

    // Object name
    obj += `o ${mesh.featureId || 'mesh'}\n`;

    // Vertices
    for (let i = 0; i < vertexCount; i++) {
      const x = mesh.vertices[i * 3]!;
      const y = mesh.vertices[i * 3 + 1]!;
      const z = mesh.vertices[i * 3 + 2]!;
      obj += `v ${x} ${y} ${z}\n`;
    }

    // Normals
    for (let i = 0; i < normalCount; i++) {
      const nx = mesh.normals[i * 3]!;
      const ny = mesh.normals[i * 3 + 1]!;
      const nz = mesh.normals[i * 3 + 2]!;
      obj += `vn ${nx} ${ny} ${nz}\n`;
    }

    // Faces (1-based indices)
    const triangleCount = Math.floor(mesh.indices.length / 3);
    for (let i = 0; i < triangleCount; i++) {
      const i0 = mesh.indices[i * 3]! + 1 + vertexOffset;
      const i1 = mesh.indices[i * 3 + 1]! + 1 + vertexOffset;
      const i2 = mesh.indices[i * 3 + 2]! + 1 + vertexOffset;
      // face v/vn format
      const n0 = mesh.indices[i * 3]! + 1 + normalOffset;
      const n1 = mesh.indices[i * 3 + 1]! + 1 + normalOffset;
      const n2 = mesh.indices[i * 3 + 2]! + 1 + normalOffset;
      obj += `f ${i0}//${n0} ${i1}//${n1} ${i2}//${n2}\n`;
    }

    obj += '\n';
    vertexOffset += vertexCount;
    normalOffset += normalCount;
  }

  return { obj };
}
