import { describe, it, expect } from 'vitest';
import { exportOBJ } from './obj-exporter';
import type { MeshData } from '../../types/cad';

function makeTriangle(): MeshData {
  return {
    featureId: 'tri',
    vertices: new Float32Array([0, 0, 0, 1, 0, 0, 0, 1, 0]),
    normals: new Float32Array([0, 0, 1, 0, 0, 1, 0, 0, 1]),
    indices: new Uint32Array([0, 1, 2]),
  };
}

function makeSecondTriangle(): MeshData {
  return {
    featureId: 'tri2',
    vertices: new Float32Array([2, 0, 0, 3, 0, 0, 2, 1, 0]),
    normals: new Float32Array([0, 0, 1, 0, 0, 1, 0, 0, 1]),
    indices: new Uint32Array([0, 1, 2]),
  };
}

describe('OBJ Exporter', () => {
  it('should produce valid OBJ with header', () => {
    const { obj } = exportOBJ([makeTriangle()]);
    expect(obj).toContain('# OpenCAD OBJ Export');
    expect(obj).toContain('# Generated by OpenCAD');
  });

  it('should include object name', () => {
    const { obj } = exportOBJ([makeTriangle()]);
    expect(obj).toContain('o tri');
  });

  it('should include vertices', () => {
    const { obj } = exportOBJ([makeTriangle()]);
    expect(obj).toContain('v 0 0 0');
    expect(obj).toContain('v 1 0 0');
    expect(obj).toContain('v 0 1 0');
  });

  it('should include normals', () => {
    const { obj } = exportOBJ([makeTriangle()]);
    expect(obj).toContain('vn 0 0 1');
  });

  it('should include face with 1-based indices', () => {
    const { obj } = exportOBJ([makeTriangle()]);
    expect(obj).toContain('f 1//1 2//2 3//3');
  });

  it('should offset indices for second mesh', () => {
    const { obj } = exportOBJ([makeTriangle(), makeSecondTriangle()]);
    const lines = obj.split('\n').filter((l) => l.startsWith('f '));
    expect(lines).toHaveLength(2);
    // Second mesh face should use offset indices (4, 5, 6 for vertices)
    expect(lines[1]).toContain('4//4 5//5 6//6');
  });

  it('should use custom name', () => {
    const { obj } = exportOBJ([makeTriangle()], 'MyModel');
    expect(obj).toContain('# MyModel OBJ Export');
  });

  it('should handle empty mesh list', () => {
    const { obj } = exportOBJ([]);
    expect(obj).toContain('# OpenCAD OBJ Export');
    expect(obj).not.toContain('v ');
  });
});
